version: '3'

services:
    proxy:
        image: nginx:1.14.1
        volumes:
          - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./etc/nginx/sites-available-docker:/etc/nginx/sites-enabled
          - ./etc/nginx/sites-available-docker:/etc/nginx/sites-available
          - ./etc/nginx/mime.types:/etc/nginx/mime.types
          - ./www/data:/www/data
        ports:
          - "80:80"
        depends_on:
          - db
          - app

    app:
        build:
            context: .
            dockerfile: ./go/Dockerfile
        command: "make run/docker"
        volumes:
          - ./go:/opt/app/go
          - ./fixture:/opt/app/fixture
        ports:
          - "1323:1323"
        environment:
          MYSQL_HOST: "db"

    db:
        image: mysql:5.6
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: isuumo
            MYSQL_USER: isucon
            MYSQL_PASSWORD: isucon
            TZ: Asia/Tokyo
        ports:
            - "33060:3306"
        volumes:
          - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
          - ./etc/mysql/conf.d:/etc/mysql/conf.d
          - ./etc/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
          - ./mysql/db/init.docker.sh:/docker-entrypoint-initdb.d/02.sh
          - ./mysql/db/:/opt/dbseed/
